### ISSUE TITLE
Add typescript declaration(s)

### ISSUE THREAD

**Issue by joeyfigaro** [Skyscanner/backpack-react-native#613]
Would be lovely if this project/your components included typings. I'm open to helping where possible if wanted. 🔥

**Comment by olliecurtis** [comment]
Hey there @joeyfigaro :wave: 

Unfortunately this is something we wouldn't put into this project, as our Backpack libraries don't support TS and there are no plans for us to support TS at this time.

Thanks for the idea/suggestion :smile:

**Comment by olliecurtis** [comment]
Closing this issue as this as per the comment above
