### ISSUE TITLE
error: package net.skyscanner.backpack.reactnative.testing does not exist : com/facebook/react/PackageList.java:80: error: cannot find symbol       new CalendarPackage(),

### ISSUE THREAD

**Issue by vijeeshin** [Skyscanner/backpack-react-native#658]
/Users/XXX/my/XXX/customernew/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:17: error: package net.skyscanner.backpack.reactnative.testing does not exist
import net.skyscanner.backpack.reactnative.testing.CalendarPackage;
                                                  ^
/Users/XXX/my/XXX/customernew/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:80: error: cannot find symbol
      new CalendarPackage(),
          ^
  symbol:   class CalendarPackage
  location: class PackageList
Note: /Users/XXX/my/XXX/customernew/android/app/src/debug/java/com/customernew/ReactNativeFlipper.java uses or overrides a deprecated API.

Above error, while debugging the app in android . Please help

 ext {
             compileSdkVersion   = 29
             targetSdkVersion    = 29
             minSdkVersion       = 21
             buildToolsVersion   = "29.0.3"
    }

kotlin_version = '1.4.10'
threetenabpVersion = '1.3.0'

package.json
-----------------------------------
"backpack-react-native": "^9.0.0"
 "react": "16.13.1",
 "react-native": "0.63.3",

**Comment by shaundon** [comment]
Hi, unfortunately we can only provide support for Skyscanner, so we can't help here. Apologies.
