### ISSUE TITLE
error: package net.skyscanner.backpack.reactnative.testing does not exist import net.skyscanner.backpack.reactnative.testing.CalendarPackage;

### ISSUE THREAD

**Issue by AahilShahzad** [Skyscanner/backpack-react-native#714]
I'm using 
backpack-react-native:13.0.0,
react-native: 0.63.3

working fine with iOS but android getting this error below 

<img width="1440" alt="Screenshot 2021-01-26 at 7 31 46 PM" src="https://user-images.githubusercontent.com/13553516/105858464-29610e80-600d-11eb-955b-50ce67a78cb6.png">

also I did add

<img width="978" alt="Screenshot 2021-01-26 at 7 33 59 PM" src="https://user-images.githubusercontent.com/13553516/105858757-7e048980-600d-11eb-9d97-f51dfae82a90.png">

please help

**Comment by olliecurtis** [comment]
Hi,

Thanks for opening an issue. Currently this is due to Backpack React Native currently having support for the latest React Native version.

We are currently working on upgrading and a new version will coming soon with newer version compatibility

Thanks again

**Comment by AahilShahzad** [comment]
thank you for respond

**Comment by AahilShahzad** [comment]
Hi 
any update please
Backpack supports for the latest React Native version??

**Comment by olliecurtis** [comment]
Hey  @AahilShahzad ,

Its in the works! We are just working on some other updates with our app and should be coming soon!

Thanks!

**Comment by olliecurtis** [comment]
If you are interested in trying this out @AahilShahzad then feel free to install and try out `15.0.0-beta.1`

Thanks!

**Comment by olliecurtis** [comment]
Hey @AahilShahzad - just to update you RN 64 support has been officially released and supported for Backpack so will be available in the latest versions.

Closing this issue now as this should hopefully solve any issues. Feel free to reopen this if there is a problem

Thanks!
